language: node_js
sudo: false
node_js:
  -  "8"
  - "10"
  - "11"
  - "node"
script:
  - "npm run lint"
  - "npm run coverage"
after_script: "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
